train_dataset:
  name: dataset.data_val.PolypObjDataset
  params:
    image_root: '/home/weiyimin/COD1/CamoDiffusion-main1/dataset/COD10K-v3/Train/Image/'
    gt_root: '/home/weiyimin/COD1/CamoDiffusion-main1/dataset/COD10K-v3/Train/GT_Object/'
    trainsize: 352

test_dataset:
  COD10K:
    name: dataset.data_val.test_dataset
    params:
      image_root: '/home/weiyimin/COD1/CamoDiffusion-main1/dataset/COD10K-v3/Test/Image/'
      gt_root: '/home/weiyimin/COD1/CamoDiffusion-main1/dataset/COD10K-v3/Test/GT_Object/'
      testsize: 352
  CAMO:
    name: dataset.data_val.test_dataset
    params:
      image_root: '/home/weiyimin/COD1/CamoDiffusion-main1/dataset/CAMO-V.1.0/CAMO-V.1.0-CVIU2019/Images/'
      gt_root: '/home/weiyimin/COD1/CamoDiffusion-main1/dataset/CAMO-V.1.0/CAMO-V.1.0-CVIU2019/GT/'
      testsize: 352
#  CHAMELEON:
#    name: dataset.data_val.test_dataset
#    params:
#      image_root: '/media/datatset/COD10K/TestDataset/CHAMELEON/Imgs/'
#      gt_root: '/media/datatset/COD10K/TestDataset/CHAMELEON/GT/'
#      testsize: 352
  NC4K:
    name: dataset.data_val.test_dataset
    params:
      image_root: '/home/weiyimin/COD1/CamoDiffusion-main1/dataset/NC4K/Imgs/'
      gt_root: '/home/weiyimin/COD1/CamoDiffusion-main1/dataset/NC4K/GT/'
      testsize: 352
#  CDS2K:
#    name: dataset.cds2k_dataset.cds2K_dataset
#    params:
#      root: '/media/datatset/CDS2K'
#      testsize: 352